#!/bin/bash

# Nacelle Microframework
# Copyright (c) Patrick Carey 2012 - 2013


echo "Running dev_appserver"

dev_appserver.py . --datastore_consistency_policy consistent --storage_path=/home/paddy/appengine_storage/ --require_indexes --enable_sendmail

echo "Exiting..."
